"""empty message

Revision ID: 35291c8315b4
Revises: a21542752a4f
Create Date: 2020-05-29 20:43:41.690692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35291c8315b4'
down_revision = 'a21542752a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
