"""empty message

Revision ID: a21542752a4f
Revises: 
Create Date: 2020-05-29 19:53:34.971679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21542752a4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.execute('UPDATE actors SET movie_id = 1 WHERE movie_id is NULL')
    op.alter_column('actors', 'movie_id', nullable=False)
    op.create_foreign_key(None, 'actors', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actors', type_='foreignkey')
    op.drop_column('actors', 'movie_id')
    # ### end Alembic commands ###
